# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Climber' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Climber
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'Toast', '~> 4.0.0'

  target 'ClimberUITests' do
    # Pods for testing
  end

end
